url: "https://github.com/Rain9876.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Yurun Song" # the name of your site, e.g. ACME Corp.
description: "UCI Computer Science PhD"
